apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-pedido
  labels:
    app: api-pedido
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-pedido
  template:
    metadata:
      labels:
        app: api-pedido
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      volumes:
        - name: app-volume
          emptyDir: {}
        # - name: secret-provider
        #   csi:
        #     driver: secrets-store.csi.k8s.io
        #     readOnly: true
        #     volumeAttributes:
        #       secretProviderClass: "secret-provider"
      containers:
        - name: {{ .Values.api.pedido.name }}
          image: {{ .Values.api.pedido.image }}
          ports:
            - containerPort: 3000
          command: ['/bin/sh', '-c']
          args:
            # - './wait-for-it.sh {{ .Values.database.connectionStringPostgresPedido }} -- ./start.sh'
            - './start.sh'
          env:
            - name: DATABASE_URL
              value: "{{ .Values.database.connectionStringPostgresPedido }}"
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.account.AWS_ACCESS_KEY_ID }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.account.AWS_SECRET_ACCESS_KEY }} 
            - name: AWS_SESSION_TOKEN
              value: {{ .Values.account.AWS_SESSION_TOKEN }} 
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: AWS_ACCOUNT_ID
              value: "{{ .Values.account.id }}"
            - name: AWS_SQS_ENDPOINT
              value: "{{ .Values.queue.AWS_SQS_ENDPOINT}}"
            - name: AWS_SQS_NOVO_PEDIDO_QUEUE_NAME
              value: "{{ .Values.queue.AWS_SQS_NOVO_PEDIDO_QUEUE_NAME}}"
            - name: AWS_SQS_PAGAMENTO_PROCESSADO_QUEUE_NAME
              value: "{{ .Values.queue.AWS_SQS_PAGAMENTO_PROCESSADO_QUEUE_NAME}}"
            - name: AWS_SQS_PEDIDO_RECEBIDO_QUEUE_NAME
              value: "{{ .Values.queue.AWS_SQS_PEDIDO_RECEBIDO_QUEUE_NAME}}"
          volumeMounts:
            - name: app-volume
              mountPath: /home/node/app/vol
              
      
        
---
apiVersion: v1
kind: Service
metadata:
  name: api-lb-service-pedido
  labels:
    app: api-pedido
spec:
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 32000
    protocol: TCP
    targetPort: 3000

  selector:
    app: api-pedido
