apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-pagamento
  labels:
    app: api-pagamento
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-pagamento
  template:
    metadata:
      labels:
        app: api-pagamento
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      volumes:
        - name: app-volume
          emptyDir: {}
        # - name: secret-provider
        #   csi:
        #     driver: secrets-store.csi.k8s.io
        #     readOnly: true
        #     volumeAttributes:
        #       secretProviderClass: "secret-provider"
      containers:
        - name: {{ .Values.api.pagamento.name }}
          image: {{ .Values.api.pagamento.image }}
          ports:
            - containerPort: 8080
          # command: ['/bin/sh', '-c']
          # args:
          #   # - './wait-for-it.sh {{ .Values.database.connectionStringPostgresPedido }} -- ./start.sh'
          #   - './start.sh'
          env:
            - name: AWS_ACCESS_KEY
              value: {{ .Values.account.AWS_ACCESS_KEY_ID }}
            - name: AWS_SECRET_KEY
              value: {{ .Values.account.AWS_SECRET_ACCESS_KEY }} 
            - name: AWS_SESSION_TOKEN
              value: {{ .Values.account.AWS_SESSION_TOKEN }}
            - name: AWS_REGION
              value: {{ .Values.account.AWS_DEFAULT_REGION }}
            - name: AWS_ACCOUNT_ID
              value: "{{ .Values.account.id }}"
            - name: AWS_ENDPOINT
              value: {{ .Values.queue.AWS_SQS_ENDPOINT}}
            - name: AWS_SQS_NOVO_PEDIDO_QUEUE_NAME
              value: {{ .Values.queue.AWS_SQS_NOVO_PEDIDO_QUEUE_NAME}}
            - name: AWS_SQS_PAGAMENTO_PROCESSADO_QUEUE_NAME
              value: {{ .Values.queue.AWS_SQS_PAGAMENTO_PROCESSADO_QUEUE_NAME}}
            - name: AWS_SQS_PEDIDO_RECEBIDO_QUEUE_NAME
              value: {{ .Values.queue.AWS_SQS_PEDIDO_RECEBIDO_QUEUE_NAME}}
            - name: POSTGRES_USER
              value: {{ .Values.database.db_username_hexafood_pagamento }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.db_password_hexafood_pagamento }}
            - name: POSTGRES_DB
              value: {{ .Values.database.db_database_hexafood_pagamento }}
            - name: POSTGRES_HOST 
              value: {{ .Values.database.db_host_hexafood_pagamento }}
          volumeMounts:
            - name: app-volume
              mountPath: /home/node/app/vol
              
      
        
---
apiVersion: v1
kind: Service
metadata:
  name: api-lb-service-pagamento
  labels:
    app: api-pagamento
spec:
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 32003
    protocol: TCP
    targetPort: 8080

  selector:
    app: api-pagamento
