apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
   name: secret-provider
spec:
  provider: aws
  secretObjects:
    - secretName: my-k8s-secrets
      type: Opaque
      data:
        - objectName: host
          key: DATABASE_HOST
        - objectName: database
          key: DATABASE_NAME
        - objectName: username
          key: DATABASE_USERNAME
        - objectName: password
          key: DATABASE_PASSWORD
        - objectName: database_url
          key: DATABASE_URL
  parameters: 
    objects: |
      - objectName: "/dev/hexaform/host"
        objectType: "ssmparameter"
        objectAlias: host
      - objectName: "/dev/hexaform/database"
        objectType: "ssmparameter"
        objectAlias: database
      - objectName: "/dev/hexaform/username"
        objectType: "ssmparameter"
        objectAlias: username
      - objectName: "/dev/hexaform/password"
        objectType: "ssmparameter"
        objectAlias: password
      - objectName: "/dev/hexaform/database_url"
        objectType: "ssmparameter"
        objectAlias: database_url