apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
   name: secret-provider
spec:
  provider: aws
  secretObjects:
    - secretName: my-k8s-secrets
      type: Opaque
      data:
        - objectName: host
          key: DATABASE_HOST
        - objectName: database
          key: DATABASE_NAME
        - objectName: username
          key: DATABASE_USERNAME
        - objectName: password
          key: DATABASE_PASSWORD
        - objectName: database_url
          key: DATABASE_URL
        - objectName: AWS_ACCESS_KEY_ID
          key: AWS_ACCESS_KEY_ID
        - objectName: AWS_SECRET_ACCESS_KEY
          key: AWS_SECRET_ACCESS_KEY
        - objectName: AWS_DEFAULT_REGION
          key: AWS_DEFAULT_REGION
        - objectName: AWS_ACCOUNT_ID
          key: AWS_ACCOUNT_ID
        - objectName: AWS_SQS_ENDPOINT
          key: AWS_SQS_ENDPOINT
        - objectName: AWS_SQS_NOVO_PEDIDO_QUEUE_NAME
          key: AWS_SQS_NOVO_PEDIDO_QUEUE_NAME
        - objectName: AWS_SQS_PAGAMENTO_PROCESSADO_QUEUE_NAME
          key: AWS_SQS_PAGAMENTO_PROCESSADO_QUEUE_NAME
        - objectName: AWS_SQS_PEDIDO_RECEBIDO_QUEUE_NAME
          key: AWS_SQS_PEDIDO_RECEBIDO_QUEUE_NAME
        - objectName: AWS_DYNAMODB_ENDPOINT
          key: AWS_DYNAMODB_ENDPOINT
  parameters: 
    objects: |
      - objectName: "/dev/hexaform/host"
        objectType: "ssmparameter"
        objectAlias: host
      - objectName: "/dev/hexaform/database"
        objectType: "ssmparameter"
        objectAlias: database
      - objectName: "/dev/hexaform/username"
        objectType: "ssmparameter"
        objectAlias: username
      - objectName: "/dev/hexaform/password"
        objectType: "ssmparameter"
        objectAlias: password
      - objectName: "/dev/hexaform/database_url"
        objectType: "ssmparameter"
        objectAlias: database_url
      - objectName: "/dev/hexaform/AWS_ACCESS_KEY_ID"
        objectType: "ssmparameter"
        objectAlias: AWS_ACCESS_KEY_ID
      - objectName: "/dev/hexaform/AWS_SECRET_ACCESS_KEY"
        objectType: "ssmparameter"
        objectAlias: AWS_SECRET_ACCESS_KEY
      - objectName: "/dev/hexaform/AWS_DEFAULT_REGION"
        objectType: "ssmparameter"
        objectAlias: AWS_DEFAULT_REGION
      - objectName: "/dev/hexaform/AWS_ACCOUNT_ID"
        objectType: "ssmparameter"
        objectAlias: AWS_ACCOUNT_ID
      - objectName: "/dev/hexaform/AWS_SQS_ENDPOINT"
        objectType: "ssmparameter"
        objectAlias: AWS_SQS_ENDPOINT
      - objectName: "/dev/hexaform/AWS_SQS_NOVO_PEDIDO_QUEUE_NAME"
        objectType: "ssmparameter"
        objectAlias: AWS_SQS_NOVO_PEDIDO_QUEUE_NAME
      - objectName: "/dev/hexaform/AWS_SQS_PAGAMENTO_PROCESSADO_QUEUE_NAME"
        objectType: "ssmparameter"
        objectAlias: AWS_SQS_PAGAMENTO_PROCESSADO_QUEUE_NAME
      - objectName: "/dev/hexaform/AWS_SQS_PEDIDO_RECEBIDO_QUEUE_NAME"
        objectType: "ssmparameter"
        objectAlias: AWS_SQS_PEDIDO_RECEBIDO_QUEUE_NAME
      - objectName: "/dev/hexaform/dynamodb_host"
        objectType: "ssmparameter"
        objectAlias: AWS_DYNAMODB_ENDPOINT
      